# https://pre-commit.com/
repos:
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort

  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-comprehensions, flake8-builtins, flake8-rst-docstrings, flake8-blind-except, flake8-bugbear, flake8-use-fstring]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782  # Must match ci/requirements/*.yml
    hooks:
      - id: mypy
        files: hydrodata

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
      - id: pyupgrade
        args:
          - "--py36-plus"
