name: hydrodata
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - OWSLib>=0.19.1
  - numpy>=1.18.1
  - numba>=0.48.0
  - urllib3>=1.25.7
  - requests>=2.23.0
  - Shapely
  - pandas>=1.0.1
  - matplotlib>=3.1.3
  - geopandas>=0.6.1
  - geojson>=2.5.0
  - descartes>=1.1.0
  - xarray>=0.15.0
  - cartopy
  - pynio
  - pseudonetcdf
  - pydap>=3.2.2
  - lxml>=4.5
  - pycurl>=7.43.0.5
  - pip:
    - rasterstats>=0.14.0
    - tables>=3.6.1
    - geocoder>=1.38.1
    - elevation>=1.0.6