name: hydrodata
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numba
  - pandas
  - matplotlib
  - geopandas
  - geojson
  - descartes
  - xarray
  - cartopy
  - dask
  - netCDF4
  - bottleneck
  - pycurl
  - lxml
  - pip:
    - rasterstats
    - tables
    - elevation
