name: hydrodata
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - matplotlib
  - descartes
  - xarray
  - cartopy
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - jupyterlab
  - pip:
    - pyproj
    - bump2version
    - wheel
    - watchdog
    - flake8
    - sphinx
    - sphinx_rtd_theme
    - sphinx-copybutton
    - nbsphinx
    - twine
    - tox
    - coverage
    - pytest-runner
    - pytest-cov
    - pytest-xdist
    - codecov
    - numpydoc
    - mypy==0.761
    - pre-commit
    - geojson
    - black
    - rasterstats
    - tables
