name: hydrodata
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - numba
  - matplotlib
  - descartes
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - pip:
    - geojson
    - rasterstats
    - tables
    - networkx
    - hydrodata
