name: hydrodata-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - owslib
  - pandas
  - matplotlib-base
  - xarray
  - scipy
  - lxml
  - geopandas
  - geojson
  - folium
  - rasterio
  - pyproj
  - networkx
  - simplejson
  - defusedxml

  - dask
  - netCDF4
  - bottleneck
  - descartes

  - isort
  - black
  - flake8
  - flake8-comprehensions
  - flake8-builtins
  - flake8-rst-docstrings
  - flake8-blind-except
  - flake8-bugbear
  - pyupgrade
  - pycodestyle
  - numpydoc

  - bump2version
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage

  - jupyterlab
  - recommonmark
  - nbsphinx
  - sphinx
  - sphinx-copybutton
  - pip:
    - flake8-use-fstring
    - git+https://github.com/bashtage/sphinx-material.git
