name: hydrodata-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - owslib
  - scipy
  - pandas
  - numba
  - matplotlib
  - descartes
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - rasterio
  - pyproj
  - networkx
  - geojson
  - simplejson
  - pytables
  - flake8
  - flake8-comprehensions
  - flake8-builtins
  - flake8-rst-docstrings
  - flake8-blind-except
  - pycodestyle
  - pytest-runner
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - numpydoc
  - coverage
  - defusedxml
  - ipykernel
  - ipython
  - sphinx
  - recommonmark
  - nbsphinx
  - geojson
  - folium
  - sphinx-markdown-tables
  - sphinx-copybutton
  - pip:
    - git+https://github.com/bashtage/sphinx-material.git
