name: hydrodata-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - owslib
  - pandas
  - matplotlib-base
  - xarray
  - scipy
  - geopandas
  - geojson
  - folium
  - rasterio
  - networkx
  - simplejson
  - defusedxml

  - dask
  - netCDF4
  - bottleneck
  - descartes

  - bump2version
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage

  - jupyterlab
  - recommonmark
  - nbsphinx
  - sphinx
  - sphinx-copybutton
  - pycodestyle
  - numpydoc
  - pip:
    - flake8-use-fstring
    - git+https://github.com/bashtage/sphinx-material.git
