name: "Build draft PDF"

on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PDF_PUSH }}

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: docs/paper.pdf
      - name: Commit and push if PDF changed
        run: |-
          git diff
          git config --global user.email "draf_pdf@example.com"
          git config --global user.name "Draf_PDF-bot"
          git diff --quiet || (git add docs/paper.pdf && git commit -m "Updated PDF version of the paper.")
          git push
