name: Linting

on:
  pull_request:
  workflow_dispatch: # allows you to trigger manually

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-python@v2
    - name: Install GDAL
      run: |-
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev libspatialindex-dev
        pip install -U \
        --global-option=build_ext \
        --global-option="-I/usr/include/gdal" \
        gdal==`gdal-config --version`
    - uses: pre-commit/action@v2.0.3
