name: CI

on: [push, pull_request]

jobs:
  test:
    name: python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
            - os: windows-latest
              python-version: 3.6

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@master
      - name: Set environment variables
        run: |-
          echo "CONDA_ENV_FILE=ci/requirements/environment.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
            hashFiles('ci/requirements/**.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: hydrodata-tests
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
      - name: Install conda dependencies
        run: |-
          cat $CONDA_ENV_FILE
          mamba env update -f $CONDA_ENV_FILE
      - name: Install hydrodata
        run: |-
          python -m pip install --no-deps -e .
      - name: Version info
        run: |-
          conda info -a
          conda list
          python -c "import hydrodata;hydrodata.show_versions()"
      - name: Run pytest
        shell: bash -l {0}
        run: |-
          mamba install -y -c conda-forge --strict-channel-priority pytest pytest-cov codecov flaky
          pytest --cov=hydrodata --cov-report term-missing --cov-report xml --verbose --color=yes
      - name: Run codecov
        uses: codecov/codecov-action@v1
